typography_spectrum: 0.28304016194306314
color:
  brandStrength: 0.33613754343241453
  lightness: 0.6075055757537484
  saturation: 0.2844586241990328
  rhythmicContrast: 0.8789858298841864
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.7635668751318008
author:
  name: Roger Calger
  email: chairman@scdpok.org
  url: www.modernoklahomastatesman.com
name: Oklahoma Statesman
title: Practical results are more important than ideological leanings.
